# Node Information
data-path = "/opt/besu/data"
genesis-file = "/opt/besu/genesis.json"
revert-reason-enabled = true

logging = "INFO"

min-gas-price = 0

# P2P network
p2p-enabled = true
discovery-enabled = true
p2p-host = "0.0.0.0"
p2p-port = 30303
max-peers = 25

host-allowlist = ["*"]

# JSON-RPC
rpc-http-api = ["DEBUG", "ETH", "ADMIN", "WEB3", "QBFT", "NET", "EEA", "PRIV", "PERM", "TXPOOL", "PLUGINS", "MINER", "TRACE"]
rpc-http-cors-origins = ["*"]
rpc-http-enabled = true
rpc-http-max-active-connections = 2000
# rpc-http-authentication-enabled = true
# rpc-http-authentication-credentials-file = "/etc/auth/auth.toml"

# GRAPHQL-RPC
graphql-http-enabled = false
graphql-http-host = "0.0.0.0"
graphql-http-port = 8547
graphql-http-cors-origins = ["*"]

# WebSockets API
rpc-ws-enabled = false
rpc-ws-host = "0.0.0.0"
rpc-ws-port = 8546
rpc-ws-api = ["DEBUG", "ETH", "ADMIN", "WEB3", "QBFT", "NET", "EEA", "PRIV", "PERM"]
rpc-ws-authentication-enabled = false

# Metrics
metrics-enabled = false
metrics-host = "0.0.0.0"
metrics-port = 9545