version: "3.4"

networks:
  besu-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.240.0/24

services:
  bootnode:
    container_name: bootnode
    image: hyperledger/besu:latest
    entrypoint:
      - /bin/bash
      - -c
      - |
        sleep 10;
        /opt/besu/bin/besu --data-path=/opt/besu/data --bootnodes=enode://$(cat /opt/besu/config/bootnode_id)@172.16.240.30:30303 --config-file=/opt/besu/config.toml --genesis-file=/opt/besu/genesis.json 
    volumes:
      - ./config.toml:/opt/besu/config.toml
      - ./genesis.json:/opt/besu/genesis.json
      - ./config:/opt/besu/config
      - ./bootnode/data:/opt/besu/data
    networks:
      besu-network:
        ipv4_address: 172.16.240.30

  node1:
    container_name: node1
    image: hyperledger/besu:latest
    entrypoint:
      - /bin/bash
      - -c
      - |
        sleep 20;
        /opt/besu/bin/besu --data-path=/opt/besu/data --bootnodes=enode://$(cat /opt/besu/config/bootnode_id)@172.16.240.30:30303 --config-file=/opt/besu/config.toml --genesis-file=/opt/besu/genesis.json 
    volumes:
      - ./config.toml:/opt/besu/config.toml
      - ./genesis.json:/opt/besu/genesis.json
      - ./config:/opt/besu/config
      - ./node1/data:/opt/besu/data
    networks:
      besu-network:
        ipv4_address: 172.16.240.31

