version: "3.4"

networks:
  besu-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.239.0/24

services:
  bootnode:
    container_name: bootnode
    image: hyperledger/besu:latest
    entrypoint:
      - /bin/bash
      - -c
      - |
        /opt/besu/bin/besu --data-path=/opt/besu/data \
        --genesis-file=/opt/besu/genesis.json \
        --rpc-http-enabled --rpc-http-cors-origins="*" \
        --min-gas-price=0 \
        --rpc-http-api=ADMIN,ETH,NET,PERM,QBFT --host-allowlist="*";

    volumes:
      - ./genesis.json:/opt/besu/genesis.json
      - /mnt/blockchain_db/node1/data:/opt/besu/data
    ports:
      - 30303:30303

    networks:
      besu-network:
        ipv4_address: 172.16.239.30

  node1:
    container_name: node1
    image: hyperledger/besu:latest

    entrypoint:
      - /bin/bash
      - -c
      - |
        /opt/besu/bin/besu --data-path=/opt/besu/data \
        --genesis-file=/opt/besu/genesis.json \
        --bootnodes=enode://29d089bc13b262344db426bd2b7055f1fae813219e750e4b082350bf3d6001dfa55e867a01a63b56849681542acc0b03f81760f1261e527f6af4b6c45acccd44@172.16.239.30:30303  \
        --rpc-http-enabled --rpc-http-cors-origins="*" \
        --min-gas-price=0 \
        --rpc-http-api=ADMIN,ETH,NET,PERM,QBFT --host-allowlist="*";

    volumes:
      - ./genesis.json:/opt/besu/genesis.json
      - /mnt/blockchain_db/node2/data:/opt/besu/data
      - ./log-config.xml:/config/log-config.xml
    depends_on:
      - bootnode
    networks:
      besu-network:
        ipv4_address: 172.16.239.31

  node2:
    container_name: node2
    image: hyperledger/besu:latest

    entrypoint:
      - /bin/bash
      - -c
      - |
        sleep 10;
        /opt/besu/bin/besu --data-path=/opt/besu/data \
        --genesis-file=/opt/besu/genesis.json \
        --bootnodes=enode://29d089bc13b262344db426bd2b7055f1fae813219e750e4b082350bf3d6001dfa55e867a01a63b56849681542acc0b03f81760f1261e527f6af4b6c45acccd44@172.16.239.30:30303  \
        --rpc-http-enabled --rpc-http-cors-origins="*" \
        --min-gas-price=0 \
        --rpc-http-api=ADMIN,ETH,NET,PERM,QBFT --host-allowlist="*" \

    volumes:
      - ./genesis.json:/opt/besu/genesis.json
      - /mnt/blockchain_db/node3/data:/opt/besu/data
      - ./log-config.xml:/config/log-config.xml
    depends_on:
      - bootnode
    networks:
      besu-network:
        ipv4_address: 172.16.239.32

  node3:
    container_name: node3
    image: hyperledger/besu:latest

    entrypoint:
      - /bin/bash
      - -c
      - |
        sleep 10;
        /opt/besu/bin/besu --data-path=/opt/besu/data \
        --genesis-file=/opt/besu/genesis.json \
        --bootnodes=enode://c7b3c1871f30f6cf1ea2b64fd2799f884bedbc00a0a62e7550ae6f68de444cbdf539d1f8d79bb34208527cfa6482ccbb5072ffc1c13b5679b9d061edaa34cc2c@172.16.239.30:30303  \
        --rpc-http-enabled --rpc-http-cors-origins="*" \
        --min-gas-price=0 \
        --rpc-http-api=ADMIN,ETH,NET,PERM,QBFT --host-allowlist="*" \

    volumes:
      - ./genesis.json:/opt/besu/genesis.json
      - /mnt/blockchain_db/node4/data:/opt/besu/data
      - ./log-config.xml:/config/log-config.xml
    ports:
      - 8545:8545
    depends_on:
      - bootnode
    networks:
      besu-network:
        ipv4_address: 172.16.239.33