version: "3.4"

networks:
  besu-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.240.0/24

services:
  bootnode:
    container_name: bootnode
    image: hyperledger/besu:latest
    entrypoint:
      - /bin/bash
      - -c
      - |
        /opt/besu/bin/besu --data-path=/opt/besu/data         --genesis-file=/opt/besu/genesis.json         --rpc-http-enabled         --rpc-http-cors-origins="*"         --min-gas-price=0         --p2p-host="0.0.0.0"         --p2p-port=30303         --p2p-enabled=true         --discovery-enabled=true         --max-peers=25         --metrics-enabled         --rpc-ws-enabled         --permissions-accounts-config-file-enabled         --permissions-accounts-config-file=/opt/besu/config/accounts_config.toml         --permissions-nodes-config-file-enabled         --permissions-nodes-config-file=/opt/besu/config/nodes_config.toml         --rpc-http-api=ADMIN,ETH,NET,PERM,QBFT
    volumes:
      - ./config.toml:/opt/besu/config.toml
      - ./genesis.json:/opt/besu/genesis.json
      - ./config/bootnode_id:/opt/besu/config/bootnode_id
      - ./config/accounts_config.toml:/opt/besu/config/accounts_config.toml
      - ./config/nodes_config.toml:/opt/besu/config/nodes_config.toml
      - ./bootnode/data:/opt/besu/data
    ports:
      - 30303:30303
      - 8545:8545
      - 8546:8546
      - 8547:8547
    networks:
      besu-network:
        ipv4_address: 172.16.240.30
  node1:
    container_name: node1
    image: hyperledger/besu:latest
    entrypoint:
      - /bin/bash
      - -c
      - |
        sleep 20;
        /opt/besu/bin/besu --data-path=/opt/besu/data         --bootnodes=enode://$(cat /opt/besu/config/bootnode_id)@172.16.240.30:30303         --config-file=/opt/besu/config.toml         --genesis-file=/opt/besu/genesis.json         --metrics-enabled         --rpc-ws-enabled         --permissions-accounts-config-file-enabled         --permissions-accounts-config-file=/opt/besu/config/accounts_config.toml         --permissions-nodes-config-file-enabled         --permissions-nodes-config-file=/opt/besu/config/nodes_config.toml         --rpc-http-api=ADMIN,ETH,NET,PERM,QBFT
    volumes:
      - ./config.toml:/opt/besu/config.toml
      - ./genesis.json:/opt/besu/genesis.json
      - ./config/bootnode_id:/opt/besu/config/bootnode_id
      - ./config/accounts_config.toml:/opt/besu/config/accounts_config.toml
      - ./config/nodes_config.toml:/opt/besu/config/nodes_config.toml
      - ./node1/data:/opt/besu/data
    depends_on:
      - bootnode
    networks:
      besu-network:
        ipv4_address: 172.16.240.31
