# Node Information
data-path="data"
genesis-file="../genesis.json"
revert-reason-enabled=true
identity="node1"

logging="INFO"

# DOCKER | KUBERNETES | AUTO | NONE
nat-method="NONE"

min-gas-price=0

# Transaction Pool
tx-pool-retention-hours=999
tx-pool-limit-by-account-percentage=1
tx-pool-max-size=20000

# P2P network
p2p-enabled=true
discovery-enabled=true
p2p-port=30303
max-peers=25

host-allowlist=["*"]

# JSON-RPC
rpc-http-api=["ADMIN", "ETH", "NET", "PERM", "QBFT"]
rpc-http-cors-origins=["*"]
rpc-http-enabled=true
rpc-http-host="0.0.0.0"
rpc-http-port=8545
rpc-http-max-active-connections=2000

# Permissioning
permissions-nodes-contract-enabled=true
permissions-nodes-contract-address="0x0000000000000000000000000000000000009999"
permissions-nodes-contract-version=2
permissions-accounts-contract-enabled=true

# GRAPHQL-RPC (keeping disabled as per original config.toml)
graphql-http-enabled=false
graphql-http-host="0.0.0.0"
graphql-http-port=8547
graphql-http-cors-origins=["*"]

# WebSockets API (keeping disabled as per original config.toml)
rpc-ws-enabled=false
rpc-ws-host="0.0.0.0"
rpc-ws-port=8546
rpc-ws-api=["DEBUG", "ETH", "ADMIN", "WEB3", "QBFT", "NET", "EEA", "PRIV", "PERM"]
rpc-ws-authentication-enabled=false

# Metrics (keeping disabled as per original config.toml)
metrics-enabled=false
metrics-host="0.0.0.0"
metrics-port=9545
